apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-tests
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: playwright-tests
        image: <your-dockerhub-username>/playwright-tests:latest
        command: ["npx", "playwright", "test", "--project=chromium,firefox"]
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Never
