apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-tests
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: playwright-tests
        image: <your-dockerhub-username>/playwright-tests:latest
        imagePullPolicy: IfNotPresent
        command: 
          - "npx"
          - "playwright"
          - "test"
          - "--project=chromium"           # ← CRITICAL: Run only Chromium
          - "--timeout=60000"
        resources:
          limits:
            memory: "1.5Gi"    # Increase memory
            cpu: "1000m"       # Full CPU
      restartPolicy: Never
  activeDeadlineSeconds: 600   # 10 minute max
